# Generated by Django 4.0.1 on 2022-08-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('success', models.IntegerField()),
                ('description', models.TextField()),
                ('count', models.IntegerField(null=0)),
                ('soil', models.IntegerField(null=0)),
                ('air', models.IntegerField(null=0)),
                ('radio', models.IntegerField(null=0)),
                ('trash', models.IntegerField(null=0)),
                ('ocean', models.IntegerField(null=0)),
                ('approval', models.IntegerField(null=0)),
                ('capital', models.IntegerField(null=0)),
                ('product', models.IntegerField(null=0)),
                ('disaster', models.IntegerField(null=0)),
                ('universe', models.IntegerField(null=0)),
                ('year', models.IntegerField(null=2000)),
            ],
        ),
    ]
